<?php

return [
  [
    'name' => 'Pasta alla carbonara',
    'price' => 12.00,
    'visible' => 1,
    'description' => 'Un piatto tradizionale italiano a base di uova, formaggio pecorino, guanciale, e pepe nero.',
    'ingredients' => 'Pasta, Uovo, Pecorino, Guanciale, Pepe nero',
    'is_vegan' => 0,
    'is_frozen' => 0,
    'is_gluten_free' => 0,
    'is_lactose_free' => 0,
    'type' => 'Italiano',
  ],
  [
    'name' => 'Pasta alla carbonara con panna',
    'price' => 10.00,
    'visible' => 1,
    'description' => 'Un piatto tradizionale italiano a base di uova, formaggio pecorino, guanciale, pepe nero e panna.',
    'ingredients' => 'Pasta, Uovo, Pecorino, Guanciale, Pepe nero, Panna',
    'is_vegan' => 0,
    'is_frozen' => 0,
    'is_gluten_free' => 0,
    'is_lactose_free' => 0,
    'type' => 'Americano',
  ],
  [
    'name' => 'Pasta alla carbonara Gourmet',
    'price' => 25.00,
    'visible' => 1,
    'description' => 'Un piatto tradizionale italiano rivisitato in chiave gourmet a base di uova di quaglia, formaggio pecorino, polvere di guanciale cotto a bassa temperatura, e pepe nero.',
    'ingredients' => 'Pasta, Uovo di quaglia, Pecorino, Guanciale, Pepe nero',
    'is_vegan' => 0,
    'is_frozen' => 0,
    'is_gluten_free' => 0,
    'is_lactose_free' => 0,
    'type' => 'Italiano',
  ],
  [
    'name' => 'Risotto alla milanese',
    'price' => 15.00,
    'visible' => 1,
    'description' => 'Un delizioso risotto cremoso con zafferano e midollo di bue.',
    'ingredients' => 'Riso, Zafferano, Midollo di bue, Brodo, Burro, Formaggio',
    'is_vegan' => 0,
    'is_frozen' => 0,
    'is_gluten_free' => 1,
    'is_lactose_free' => 0,
    'type' => 'Italiano',
  ],
  [
    'name' => 'Pizza margherita',
    'price' => 8.50,
    'visible' => 1,
    'description' => 'La pizza classica con pomodoro, mozzarella e basilico.',
    'ingredients' => 'Farina, Acqua, Lievito, Sale, Pomodori, Mozzarella, Olio, Basilico',
    'is_vegan' => 0,
    'is_frozen' => 0,
    'is_gluten_free' => 0,
    'is_lactose_free' => 0,
    'type' => 'Italiano',
  ],
  [
    'name' => 'Spaghetti alle vongole',
    'price' => 13.00,
    'visible' => 1,
    'description' => 'Spaghetti con vongole veraci, aglio, olio e prezzemolo.',
    'ingredients' => 'Spaghetti, Vongole, Aglio, Olio, Prezzemolo',
    'is_vegan' => 0,
    'is_frozen' => 0,
    'is_gluten_free' => 0,
    'is_lactose_free' => 1,
    'type' => 'Italiano',
  ],
  [
    'name' => 'Lasagna alla bolognese',
    'price' => 14.00,
    'visible' => 1,
    'description' => 'ragù alla bolognese e besciamella.',
    'ingredients' => 'Sfoglia all\'uovo, Ragù alla bolognese, Besciamella',
    'is_vegan' => 0,
    'is_frozen' => 0,
    'is_gluten_free' => 0,
    'is_lactose_free' => 0,
    'type' => 'Italiano',
  ],

  [
    'name' => 'Penne all\'arrabbiata',
    'price' => 9.00,
    'visible' => 1,
    'description' => 'Pasta con salsa di pomodoro piccante, aglio, peperoncino rosso e prezzemolo.',
    'ingredients' => 'Pasta, Pomodoro, Aglio, Peperoncino, Olio, Prezzemolo',
    'is_vegan' => 1,
    'is_frozen' => 0,
    'is_gluten_free' => 0,
    'is_lactose_free' => 1,
    'type' => 'Italiano',
  ],
  [
    'name' => 'Tiramisu',
    'price' => 6.00,
    'visible' => 1,
    'description' => 'Dolce a strati con savoiardi, caffè, mascarpone, cacao e uova.',
    'ingredients' => 'Savoiardi, Caffè, Mascarpone, Cacao, Uova, Zucchero',
    'is_vegan' => 0,
    'is_frozen' => 0,
    'is_gluten_free' => 0,
    'is_lactose_free' => 0,
    'type' => 'Italiano',
  ],
  [
    'name' => 'Panna Cotta',
    'price' => 6.50,
    'visible' => 1,
    'description' => 'Dolce alla crema con gelatina e guarnito con salsa di frutti di bosco o caramello.',
    'ingredients' => 'Panna, Zucchero, Vaniglia, Gelatina, Salsa di frutti di bosco o caramello',
    'is_vegan' => 0,
    'is_frozen' => 0,
    'is_gluten_free' => 1,
    'is_lactose_free' => 0,
    'type' => 'Italiano',
  ],
  [
    'name' => 'Tortellini in brodo',
    'price' => 10.00,
    'visible' => 1,
    'description' => 'Tortellini ripieni di carne serviti in brodo di carne.',
    'ingredients' => 'Tortellini, Brodo di carne',
    'is_vegan' => 0,
    'is_frozen' => 0,
    'is_gluten_free' => 0,
    'is_lactose_free' => 1,
    'type' => 'Italiano',
  ],
  [
    'name' => 'Ossobuco alla milanese',
    'price' => 17.00,
    'visible' => 1,
    'description' => 'Stinco di vitello brasato con verdure, brodo e vino bianco, servito con gremolata.',
    'ingredients' => 'Stinco di vitello, Verdure, Brodo, Vino bianco, Gremolata',
    'is_vegan' => 0,
    'is_frozen' => 0,
    'is_gluten_free' => 1,
    'is_lactose_free' => 1,
    'type' => 'Italiano',
  ],
  [
    'name' => 'Gnocchi di patate',
    'price' => 9.50,
    'visible' => 1,
    'description' => 'Gnocchi fatti in casa con patate e farina, serviti con salsa di pomodoro e basilico.',
    'ingredients' => 'Patate, Farina, Salsa di pomodoro, Basilico',
    'is_vegan' => 1,
    'is_frozen' => 0,
    'is_gluten_free' => 0,
    'is_lactose_free' => 1,
    'type' => 'Italiano',
  ],
  [
    'name' => 'Pesto alla genovese',
    'price' => 9.00,
    'visible' => 1,
    'description' => 'Pasta condita con un sugo di basilico, pinoli, aglio, sale, formaggio pecorino e olio d\'oliva.',
    'ingredients' => 'Pasta, Basilico, Pinoli, Aglio, Sale, Formaggio pecorino, Olio d\'oliva',
    'is_vegan' => 0,
    'is_frozen' => 0,
    'is_gluten_free' => 0,
    'is_lactose_free' => 0,
    'type' => 'Italiano',
  ],
  [
    'name' => 'Carpaccio di manzo',
    'price' => 14.00,
    'visible' => 1,
    'description' => 'Fette sottili di manzo crudo, condite con olio d\'oliva, succo di limone, sale e pepe.',
    'ingredients' => 'Manzo, Olio d\'oliva, Succo di limone, Sale, Pepe',
    'is_vegan' => 0,
    'is_frozen' => 0,
    'is_gluten_free' => 1,
    'is_lactose_free' => 1,
    'type' => 'Italiano',
  ],
  [
    'name' => 'Polenta con funghi e salsiccia',
    'price' => 11.00,
    'visible' => 1,
    'description' => 'Polenta cremosa servita con funghi e salsiccia saltati.',
    'ingredients' => 'Polenta, Funghi, Salsiccia, Olio, Aglio',
    'is_vegan' => 0,
    'is_frozen' => 0,
    'is_gluten_free' => 1,
    'is_lactose_free' => 1,
    'type' => 'Italiano',
  ],
  [
    'name' => 'Gelato alla vaniglia',
    'price' => 4.50,
    'visible' => 1,
    'description' => 'Gelato cremoso alla vaniglia fatto in casa.',
    'ingredients' => 'Latte, Panna, Zucchero, Vaniglia',
    'is_vegan' => 0,
    'is_frozen' => 1,
    'is_gluten_free' => 1,
    'is_lactose_free' => 0,
    'type' => 'Italiano',
  ],
  [
    'name' => 'Doner Kebab',
    'price' => 6.75,
    'visible' => 1,
    'description' => 'Doner Kebab, il classico kebab direttamente dalla Turchia.',
    'ingredients' => 'Piadina, Carne, Insalata, Pomodori, Cipolla,Patatine, Salsa Yogurt',
    'is_vegan' => 0,
    'is_frozen' => 0,
    'is_gluten_free' => 0,
    'is_lactose_free' => 0,
    'type' => 'Turco',
  ],
  [
    'name' => 'Pizza Kebab',
    'price' => 7.50,
    'visible' => 1,
    'description' => 'Pizza Kebab, quando la Turchia incontra l\'italia.',
    'ingredients' => 'Farina, Carne, Insalata, Salsa di pomodoro, Mozzarella, Patatine, Salsa Yogurt',
    'is_vegan' => 0,
    'is_frozen' => 0,
    'is_gluten_free' => 0,
    'is_lactose_free' => 0,
    'type' => 'Italiano, Turco',
  ],
  [
    'name' => 'Panino con Hamburger completissimo',
    'price' => 9.50,
    'visible' => 1,
    'description' => 'Il panino con Hamburger più americano che ci sia',
    'ingredients' => 'Pane, Carne, Insalata, Cheddar, Salsa BBQ, Maionese, Ketchup, Bacon, Anelli di cipolla fritti, Patatine',
    'is_vegan' => 0,
    'is_frozen' => 0,
    'is_gluten_free' => 0,
    'is_lactose_free' => 0,
    'type' => 'Americano',
  ],
  [
    'name' => 'Pollo Fritto XL',
    'price' => 14.50,
    'visible' => 1,
    'description' => 'Il miglior pollo fritto di tutta l\'Italia',
    'ingredients' => 'Pollo, Pastella, Cornflakes, Sale, Pepe, Olio di semi',
    'is_vegan' => 0,
    'is_frozen' => 0,
    'is_gluten_free' => 0,
    'is_lactose_free' => 0,
    'type' => 'Americano',
  ],
  [
    'name' => 'Nuggets di Pollo (4 pz.)',
    'price' => 4.00,
    'visible' => 1,
    'description' => 'Piccole pepite di pollo con un gusto incredibile',
    'ingredients' => 'Pollo, Pastella, Cornflakes, Sale, Pepe, Olio di semi',
    'is_vegan' => 0,
    'is_frozen' => 0,
    'is_gluten_free' => 0,
    'is_lactose_free' => 0,
    'type' => 'Americano',
  ],
  [
    'name' => 'Nuggets di Pollo (4 pz.)',
    'price' => 4.50,
    'visible' => 1,
    'description' => 'Piccole pepite di pollo con un gusto incredibile',
    'ingredients' => 'Pollo, Pastella, Cornflakes, Sale, Pepe, Olio di semi',
    'is_vegan' => 0,
    'is_frozen' => 0,
    'is_gluten_free' => 0,
    'is_lactose_free' => 0,
    'type' => 'Americano',
  ],
  [
    "name" => 'Pizza Quattro Formaggi',
    "price" => 8.00,
    'visible' => 1,
    "description"=> 'Pizza ai quattro formaggi',
    "ingredients" => "Mozzarella, Grana, Gorgonzola, Scamorza",
    'is_vegan' => 0,
    'is_frozen' => 0,
    'is_gluten_free' => 0,
    'is_lactose_free' => 0,
    'type' => 'Italiano',
  ],
  [
    "name" => 'Pizza Diavola',
    "price" => 7.00,
    'visible' => 1,
    "description"=> 'Pizza diavola',
    "ingredients" => "Mozzarella, Pomodoro, Salame",
    'is_vegan' => 0,
    'is_frozen' => 0,
    'is_gluten_free' => 0,
    'is_lactose_free' => 0,
    'type' => 'Italiano',
  ],
  [
    "name" => 'Pizza Marinara',
    "price" => 4.00,
    'visible' => 1,
    "description"=> 'Pizza marinara',
    "ingredients" => "Mozzarella, Pomodoro, Origano, Aglio",
    'is_vegan' => 0,
    'is_frozen' => 0,
    'is_gluten_free' => 0,
    'is_lactose_free' => 0,
    'type' => 'Italiano',
  ],
  [
    "name" => 'Pizza Capricciosa',
    "price" => 8.00,
    'visible' => 1,
    "description"=> 'Pizza capricciosa',
    "ingredients" => "Mozzarella, Pomodoro, Prosciutto, Funghi, Carciofini",
    'is_vegan' => 0,
    'is_frozen' => 0,
    'is_gluten_free' => 0,
    'is_lactose_free' => 0,
    'type' => 'Italiano',
  ],
  [
    "name" => 'Pizza con Salsiccia',
    "price" => 7.00,
    'visible' => 1,
    "description"=> 'Pizza con salsiccia',
    "ingredients" => "Mozzarella, Pomodoro, Salsiccia",
    'is_vegan' => 0,
    'is_frozen' => 0,
    'is_gluten_free' => 0,
    'is_lactose_free' => 0,
    'type' => 'Italiano',
  ],
  [
    "name" => 'Pizza Margherita Veg',
    "price" => 9.00,
    'visible' => 1,
    "description"=> 'Pizza margherita vegana',
    "ingredients" => "Mozzarella di soia, Pomodoro, Basilico",
    'is_vegan' => 1,
    'is_frozen' => 0,
    'is_gluten_free' => 0,
    'is_lactose_free' => 1,
    'type' => 'Italiano',
  ],
  [
    "name" => 'Pizza Napoli',
    "price" => 6.00,
    'visible' => 1,
    "description"=> 'Pizza napoli, forza napoli',
    "ingredients" => "Mozzarella, Pomodoro, Basilico",
    'is_vegan' => 0,
    'is_frozen' => 0,
    'is_gluten_free' => 0,
    'is_lactose_free' => 0,
    'type' => 'Italiano',
  ],
  [
    "name" => 'Pizza Ortolana Veg',
    "price" => 8.00,
    'visible' => 1,
    "description"=> 'Pizza ortolana vegana',
    "ingredients" => "Mozzarella vegana, Pomodoro, Zucchine, Melanzane, Peperoni",
    'is_vegan' => 1,
    'is_frozen' => 0,
    'is_gluten_free' => 0,
    'is_lactose_free' => 1,
    'type' => 'Italiano',
  ],
  [
    "name" => 'Pizza Cocciuto',
    "price" => 10.00,
    'visible' => 1,
    "description"=> 'Pizza vegana senza lattosio',
    "ingredients" => "Fiori di Zucca, Pomodori Secchi, Pesto di Basilico",
    'is_vegan' => 1,
    'is_frozen' => 0,
    'is_gluten_free' => 1,
    'is_lactose_free' => 1,
    'type' => 'Italiano',
  ],
];
