<?php

return [
  [
    "name"=> "Domò Sushi",
    "slug"=> "",
    "iva"=> "",
    "email"=> "domosushirestaurant@gmail.com",
    "telephone-number"=> "06 4425 4635",
    "address"=> "Via Novara 21, 00198 Roma Italia",
    "image-path"=> "/img-restaurants/domo-sushi.jpg",
    "image-name"=> "domo-sushi.jpg",
    "raiting"=> "",
  ],
  [
    "name"=> "Don's - Meats & Spirits",
    "slug"=> "",
    "iva"=> "",
    "email"=> "info@meatsandspirits.it",
    "telephone-number"=> "334 571 0863",
    "address"=> "Vicolo delle Vacche 9, 00186 Roma Italia",
    "image-path"=> "/img-restaurants/don-s.jpg",
    "image-name"=> "don-s.jpg",
    "raiting"=> "",
  ],
  [
    "name"=> "Bufalero",
    "slug"=> "",
    "iva"=> "",
    "email"=> "bufalero2019@gmail.com",
    "telephone-number"=> "06 5987 8731",
    "address"=> "Via Passo del Turchino 18, 00139 Roma Italia",
    "image-path"=> "/img-restaurants/bufalero.jpg",
    "image-name"=> "bufalero.jpg",
    "raiting"=> "",
  ],
  [
    "name"=> "Assunta Madre",
    "slug"=> "",
    "iva"=> "",
    "email"=> "assuntamadreroma@gmail.com",
    "telephone-number"=> "342 746 4435",
    "address"=> "Via Giulia 14, 00186 Roma Italia",
    "image-path"=> "/img-restaurants/assunta-madre.jpg",
    "image-name"=> "assunta-madre.jpg",
    "raiting"=> "",
  ],
  [
    "name"=> "'DOC' Cruderia EnoBistrot",
    "slug"=> "",
    "iva"=> "",
    "email"=> "doccruderiabistrot@gmail.com",
    "telephone-number"=> "342 746 4435",
    "address"=> "Via Pietro Manzi 1 Angolo Viale Trastevere, 00153 Roma Italia",
    "image-path"=> "/img-restaurants/doc.jpg",
    "image-name"=> "doc.jpg",
    "raiting"=> "",
  ],
  [
    "name"=> "il Signore degli Agnelli",
    "slug"=> "",
    "iva"=> "",
    "email"=> "risto.ilsignoredegliagnelli@gmail.com",
    "telephone-number"=> "389 908 7255",
    "address"=> "Via Flaminia 573 ABCD Incrocio con Corso Francia, 00191 Roma Italia",
    "image-path"=> "/img-restaurants/il-Ssgnore-degli-agnelli.jpg",
    "image-name"=> "il-Ssgnore-degli-agnelli.jpg",
    "raiting"=> "",
  ],
  [
    "name"=> "La Fata Ignorante - Rooftop Restaurant & Bar",
    "slug"=> "",
    "iva"=> "",
    "email"=> "gdmgdm@hotmail.com",
    "telephone-number"=> "324.7474306",
    "address"=> "Via Firenze, 8, 00184 Roma Italia",
    "image-path"=> "/img-restaurants/la-fata-ignorante.jpg",
    "image-name"=> "la-fata-ignorante.jpg",
    "raiting"=> "",
  ],
  [
    "name"=> "Trecaffè Due Macelli",
    "slug"=> "",
    "iva"=> "",
    "email"=> "info@trecaffe.it",
    "telephone-number"=> "06 679 0741",
    "address"=> "Via dei Due Macelli 107, 00187 Roma Italia",
    "image-path"=> "/img-restaurants/trecaffe-due-macelli.jpg",
    "image-name"=> "trecaffe-due-macelli.jpg",
    "raiting"=> "",
  ],
  [
    "name"=> "Mimì e Cocò Trast",
    "slug"=> "",
    "iva"=> "",
    "email"=> "info@mimiecoco.com",
    "telephone-number"=> "06 9357 7886",
    "address"=> "Via della Scala 1, 00153 Roma Italia",
    "image-path"=> "/img-restaurants/mimi-e-coco-trast.jpg",
    "image-name"=> "mimi-e-coco-trast.jpg",
    "raiting"=> "",
  ],
  [
    "name"=> "Quanto Basta Slow Restaurant",
    "slug"=> "",
    "iva"=> "",
    "email"=> "quantobastaristorante@gmail.com",
    "telephone-number"=> "06 9193 8937",
    "address"=> "Via Padre Massaruti, 183/185, 00125 Roma Italia",
    "image-path"=> "/img-restaurants/quanto-basta-slow-restaurant.jpg",
    "image-name"=> "quanto-basta-slow-restaurant.jpg",
    "raiting"=> "",
  ],
  [
    "name"=> "Pizza Zizza Caffetteria Birreria Desserteria",
    "slug"=> "",
    "iva"=> "",
    "email"=> "jubbo16@libero.it",
    "telephone-number"=> "3458280000",
    "address"=> "Via Delle Fornaci 11, 00165 Roma Italia",
    "image-path"=> "/img-restaurants/pizza-zizza-caffetteria-birreria-desserteria.jpg",
    "image-name"=> "pizza-zizza-caffetteria-birreria-desserteria.jpg",
    "raiting"=> "",
  ]
];
